# Generated by Django 5.0.7 on 2025-02-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bus", "0003_country_day_remove_route_time_route_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
