# Generated by Django 5.0.7 on 2025-02-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bus", "0004_route_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="guest_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="guest_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="guest_phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
