# Generated by Django 5.0.7 on 2025-02-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bus", "0005_booking_guest_email_booking_guest_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="students",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="booking",
            name="adults",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="booking",
            name="children",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
